- virtualbox_builder/virtualbox_builder.sh
Signed-off-by: Ma, Mark <Mark.Ma@emc.com>
> Support build vagrant box in parallel

- data_generater/fru_gen.py
set the bin file as argument instead of hard-code
> update fru_gen.py file:

- data_generater/fru_gen.py
one command will generate one or all fru data of a server
> update fru_gen.py to make it more intellignet:

- data_generater/gen_emu_utility.py
> 1. Fix threshold-based sensors check

- packer/Vagrantfile
- packer/http/preseed.cfg
- packer/infrasim-box.json
- packer/infrasim-vmware.json
- packer/scripts/base.sh
- packer/scripts/cleanup.sh
- packer/scripts/dep.sh
- packer/scripts/dhcp_setting.sh
- packer/scripts/infrasim-compute.sh
- packer/scripts/vagrant.sh
- packer/scripts/vmware.sh
- packer/scripts/zerodisk.sh
including:
1.two json files for box and ova build 
2.one vagrantfile for box deploy 
3.one configure file for os install 
4.some shell scripts for software install and upgrade
> check in the files for packer build:

- README.md
- deb_builder/README.md
- deb_builder/openipmi-package.sh
- deb_builder/qemu-package.sh
@xiar @fub2 @turtle-fly @PaynePei
> Check in openipmi qemu deb package builder scripts.

- deb_builder/openipmi-package.sh
- deb_builder/qemu-package.sh
change the install path of qemu and openipmi to "/usr/local/bin/"
> udpate deb install scripts for qemu and openipmi:

- packer/infrasim-vmware.json
- packer/scripts/dhcp_setting.sh
- packer/scripts/infrasim-compute.sh
1.install infrasim-compute with source code instead of python library 2.fix some typos
> update scripts for packer build:

- packer/infrasim-vmware.json
Add open-vm-tools to make IP addresses and DNS Name display on Vsphere client.
> Modify infrasim-vmware.json

- packer/infrasim-vmware.json
- packer/scripts/infrasim.yml
Use this configuration file to replace the original one from init to support OVA, BOX build.
> Add a multi-bridge mode infrasim.yml for infrasim-compute

- packer/Vagrantfile
Set vm name to "infrasim-compute"
> Set vm name in Vagrantfile for box

- packer/README.md
Add a README file under packer directory on how to build box/ova.
> Add README for packer build images

- packer/infrasim-vmware.json
- packer/scripts/infrasim-vmware/nested.sh
Enable nested option for EXSi installation.
> Enable nested option in kvm_intel

- packer/infrasim-box.json
- packer/scripts/infrasim-box/boot_setting.sh
- packer/scripts/infrasim-box/dhcp_setting.sh
- packer/scripts/infrasim-vmware/boot_setting.sh
- packer/scripts/infrasim-vmware/dhcp_setting.sh
Move promisc mode setting from rc.local to interfaces
> Update promisc mode setting for ova/box

- packer/scripts/infrasim-compute.sh
- packer/scripts/infrasim.yml
1) Specify "name" in yaml file.
2) Move default yaml file to .node_map directory.
> Modify default yaml file for new CLI

- packer/scripts/infrasim.yml
"controller" key is removed. Update ova yaml file to match the new
structure.
> Update: YAML structure changes

- diag_arp_flux/diag_arp_flux.py
> Add utility to fix ARP flux

- @scale/README.md
- @scale/vagrant_libvirt/README.md
- @scale/vagrant_libvirt/Vagrantfile
- @scale/vagrant_vsphere/README.md
- @scale/vagrant_vsphere/Vagrantfile
This PR is Vagrant example file for @scale deployment on vSphere and Libvirt provider.
Wiki Page - **Vagrant and Libvirt plugin for @scale deployment**
https://github.com/InfraSIM/infrasim-compute/wiki/Vagrant-and-Libvirt-plugin-for-@scale-deployment
Wiki Page - **Vagrant and vSphere plugin for @scale deployment**
https://github.com/InfraSIM/infrasim-compute/wiki/Vagrant-and-vSphere-plugin-for-@scale-deployment
> @scale/vagrant file for @scale deployment

- fru_data_parser/fru_model.py
1. Board info area failed to sync after any set
2. Board fru file id made structure wrong
> Fix fru data sync issue

- docker/Dockerfile
- docker/README.md
- docker/docker.sh
1. Docker file, which can used to build a docker image
2. docker.sh which creates docker environment and up infrasim container
> infrasim-compute docker container

- docker/README.md
- docker/cleanup.sh
- docker/docker.sh
1. Fix issue mentioned by Peter.P.
2. Add a cleanup.sh to teardown infrasim-compute containers and ovs
environment.
3. Change README.md line separators from CRLF to LF.
> docker.sh refinement

- docker/docker.py
1. change image name to "infrasim/infrasim-compute"
2. fix bug. wrong exception raised.
@fub2 @xiar @turtle-fly @XiaowenJiang @chenc52 @chenge3 @JuneZhou19
> fix bug and change image name.

- docker/Dockerfile
- docker/docker.py
@fub2 @turtle-fly @JuneZhou19 @chenc52 @xiar @chenge3 
1. change user/password of image for SSH in Dockerfile
2. add clean up code in docker.py
> change code for puffer test

- docker/README.md
@fub2 @weia5-emc @turtle-fly @XiaowenJiang
> Note user to configure infrasim network for docker.py is supporting

- deb_builder/qemu-package.sh
@InfraSIM/infrasim_dev
build name will be like:
infrasim-qemu_2.10.1-ubuntu-xenial-1_amd64.deb
infrasim version display will be like:
QEMU : QEMU emulator version 2.10.1(infrasim-qemu ubuntu-xenial build-1)
> fix qemu version display

- deb_builder/qemu-package.sh
> Add qemu release number into infrasim version display.

- docker/docker.py
Signed-off-by: Echo Cheng <echo.cheng@emc.com>
@chenge3 @xiar @fub2 @XiaowenJiang @weia5-emc
> Bind container to 2 CPU of host VM.

- packer/infrasim-box.json
point to 16.04.3 Ubuntu iso, correct checksum
> point to correct iso and update checksum

- drive_error_injection_cli.py
Signed-off-by: Bin Yan <bin.yan1@emc.com>
> Add NVMe error injection cli

- error_injection/drive_error_injection_cli.py
User can start error injection with `-N [nodename]`
Signed-off-by: Bin Yan <bin.yan1@emc.com>
> Error Injection: Add parameter 'nodename'

- docker/docker.py
- docker/infrasim-node.yml.template
1. Adjust CPU/MEM binding upon container start
2. Use fixed mac address if use yml jinja2 template to start infrasim.  Normal Yml file is also supported.
@chenge3 @fub2 @xiar
> Adjust CPU/MEM binding upon container start, use fixed mac address.

- packer/infrasim-vmware.json
Update vCPU count from 2 to 4 in ova build
Signed-off-by: Echo Cheng <echo.cheng@emc.com>
@xiar @chenc52 @fub2
> Update vCPU count from 2 to 4 in ova build

- error_injection/drive_error_injection_cli.py
Add scsi_logpage, scsi_status, scsiclear command
> Add scsi_logpage, scsi_status, scsiclear command

- data_generater/gen_emu_utility.py
Signed-off-by: Julie Jiang <julie.jiang@emc.com>
> Modify gen_emu_utility.py to add all accessible fru from 0-0xfe

- deb_builder/openipmi-package.sh
Update openipmi package build script
> Update openipmi package build script

- packer/infrasim-box.json
- packer/scripts/infrasim-compute.sh
update packer build box config file
> update packer build box config file

- docker/Dockerfile
1. Update DEBIAN_FRONTEND noninteractive as environment variables
2. Add public bintray "deb https://dl.bintray.com/infrasim/deb xenial main"
to apt sources list for infrasim init
@xiar @fub2
> Update Dockerfile to install infrasim debain packages

- packer/infrasim-vmware.json
1. vnc_bind_address setting bind to all interfaces for VNC
2. prepare the resolv.conf file in workspace
> Add "vnc_bind_address" setting and change the dns file path

- packer/scripts/infrasim-compute.sh
Add requests install into infrasim-compute.sh to fix
ssl verify issue during packer build.
> Add requests install into infrasim-compute script

- packer/scripts/infrasim-compute.sh
add python package: netifaces for infrasim-compute setup
> update infrasim-compute.sh for packer OVA build
